# Magic Mirrors mod config
# Thu Jul 2 13:45:05 CDT 2026
# 1 second = 20 ticks!

# Interval from magic mirror is used and player is teleported in milliseconds. Default: 750. Range: 0 ~ 5000.
delay-before-teleport=750
# Is magic mirror can be used in other dimensions. Default: false. true or false.
can-use-in-other-dimensions=false
# Experience taken after use. Default: 0. Range: 0 ~ infinity.
cost-in-xp-levels=0
# Damage dealt after use (in half hearts). Default: 1. Range: 0 ~ infinity.
damage-after-use=1
# Mirror cooldown in ticks. Default: 400. Range: 0 ~ infinity.
magic-mirror-cooldown=400
# Durability decreased after use. Default: 1. Range: 0 ~ infinity.
item-damage-after-use=1
# Durability of item, zero means item is unbreakable. Default: 64. Range: 0 ~ infinity.
item-durability=64
